### ISSUE TITLE
Backspace Key

### ISSUE THREAD

**Issue by Nick-us** [velorek1/C-edit#4]
I do not understand why the backspace key does not delete the characters as in any normal editor

**Comment by velorek1** [comment]
"Not yet!" :)  This editor is far from finished. 
I'm still adding features and correcting bugs.  
I'll address this right away as soon I have the time.  
Thank for your feedback. Also, feel free to modify it as well.

**Comment by Nick-us** [comment]
Thank you for the explanation. And congratulations for the initiative! It's getting really good!
